### ISSUE TITLE
Не работает с тестами, которые открываются в новом окне

### ISSUE THREAD

**Issue by mkzung** [naloaty/syncshare-extension#2]
Привет! Расширение не показывает ответы к тестам, которые открываются в новом окне. Есть ли способ это исправить?

**Comment by Naloaty** [comment]
Приветствую! Судя по логам, проблема связана с неверной работой парсера страницы, если она открывается в новом окне. В результате сервер атвоматически отклоняет данные теста, поскольку отсутствуют необходимые поля. Соответственно, нет данных - нет ответов.

Проблема на уровне самого расширения, поэтому исправить можно только в следующей версии.

**Comment by mkzung** [comment]
Я думаю, тут дело в том, что это уже ЮУрГУ что-то мудрит...
На экзаменах в основном так тесты открываются, нельзя ничего скопировать, все становится некликабельным, кроме выбора ответов и кнопки сабмита.

**Comment by Naloaty** [comment]
Поддерживается, но может работать некорректно из-за измений в последних версиях Google Chrome (> 97.0.4692.99). В частности, некорректная работа связана с правами доступа. По какой-то причине расширение не может установить соединение с онлайн-сервисами, если ему не предоставлен полный доступ к сайту. 

Чтобы исправить данную проблему, необходимо перейти по пути
"Настройки" -> "Расширения" -> "SyncShare" -> "Сведения", затем переключить пункт "Доступ к сайтам" в положение "На всех сайтах".

**Comment by kerqM** [comment]
Здравствуйте ,хотел спросить . Расширение опять не работает ,обновил хром . Заработал ,пару тестов решил и опять расширение перестало работать . С чем это связано и в случае если идёт обновление расширение ,когда снова заработает ?

**Comment by naloaty** [comment]
Исправлено в вресии 0.1.12
