### ISSUE TITLE
Не работает расширение

### ISSUE THREAD

**Issue by JohnBlock74** [naloaty/syncshare-extension#3]
Здравствуйте. Подскажите пожалуйста, при работе с данным расширением возникает проблема и на Google Chrome и на Mozilla FireFox, что сервера недоступны?
Вы поддерживаете данный проект?
Как то можно исправить данную проблему?
Заранее огромное спасибо!

**Comment by naloaty** [comment]
Приветствую! Проект по прежнему поддерживается, однако в момент пиковой нагрузки сервисы расширения могут быть не доступны. К сожалению, у меня нет возможности увеличить мощность сервера, поскольку текущего количества добровольных пожертоваваний едва хватает на оплату даже самого минимального тарифа. Как-то так.
