### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by yarkylz** [naloaty/syncshare-extension#5]
https://syncshare.naloaty.me/analytics/api/collect выдаёт 502 Bad gateway. Соответственно, к апи доступа нет, расширение не работает.

**Comment by naloaty** [comment]
Приветствую!
Данный эндпоинт отвечает за аналитику и был намеренно отключён, чтобы снизить нагрузку на сервер. Основной API работает в обычном режиме, однако иногда может не отвечать (работа над этим уже ведется).
