### ISSUE TITLE
CORS Policy

### ISSUE THREAD

**Issue by Kuzuru** [naloaty/syncshare-extension#6]
На текущий момент на некоторых тестах попросту не появляется magic-wand. Заглянув в консоль обнаружилось, что наблюдаются проблемы с политиками CORS. Если есть какая-то информация по этому поводу, то коммьюнити бы хотело об этом узнать))

Заранее спасибо!

Прилагаю скрин:
![image](https://user-images.githubusercontent.com/49472529/224570740-99328194-119d-4190-ad29-aa84fabfede0.png)

**Comment by naloaty** [comment]
Привет! Данная ошибка связана с тем, что некоторое время назад был намеренно отключен сбор аналитики с целью снижения нагрузки на сервер. На основную функциональность это не влияет.

Однако хотелось бы отметить, что палочка появляется только в том случае, если для конкретного вопроса в тесте есть хоть какие-нибудь данные. Поэтому если нечего показывать, то и полочки нет :)

**Comment by Kuzuru** [comment]
Понял, спасибо большое!
